[project]
name = "tailwhip"
version = "0.14.0"
description = "A pure Python Tailwind CSS class sorter that works with any HTML or CSS file, including Django templates and other template languages."
readme = "README.md"
authors = [
    { name = "Martin Mahner", email = "martin@mahner.org" }
]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3 :: Only",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.11"
dependencies = [
    "dynaconf",
    "rich",
    "typer",
    "wcmatch",
]

[project.urls]
Homepage = "https://github.com/bartTC/tailwhip/"
Repository = "https://github.com/bartTC/tailwhip/"
Documentation = "https://barttc.github.io/tailwhip/"
Changelog = "https://github.com/bartTC/tailwhip/blob/main/CHANGELOG.md"
"Bug Tracker" = "https://github.com/bartTC/tailwhip/issues"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "ruff",
]

[project.scripts]
tailwhip = "tailwhip:main"

[tool.uv]
package = true

[tool.uv.build-backend]
module-root = ""

[tool.ruff]
lint.select = ["ALL"]
lint.ignore = [
    # Valid exclusions.
    "COM812", # Conflicts with ruff format
    "CPY001", # Missing copyright notice
    "E501", # Line too long (>88)
    "D203", # incorrect-blank-line-before-class (conflicts with D211)
    "D212", # Don't require summary on first line
    "ERA001", # Found commented-out code
    "FBT", # Flake Boolean Trap (don't use arg=True in functions)
    "FIX", # Line contains TODO/FIXME. Consider resolving.
    "T201", # print found 

]

[tool.ruff.lint.extend-per-file-ignores]
"test*.py" = [
    "S101", # Use of `assert` detected
    "PLR2004", # Magic value used in comparison, consider replacing <int> with a constant variable
]

[tool.pytest.ini_options]
python_files = ["*.py"]

[tool.coverage]
run.source = [
    "tailwhip",
]
run.omit = [
    "tailwhip/tests/*",
    "benchmark.py",
]
report.exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
]